language: node_js
node_js:
- 0.10.18
notifications:
  email: chris.dzoba@creativelive.com
after_success:
- cd ..
- ls
- tar cvfz travis.tgz travis/
- ls
- du -h travis.tgz
- echo $TEST_VAR
env:
  global:
    secure: KyVMBbPDuwigox2f3i5aIZB+T1Y/F/ZYt9JFqGylJMZYsDMtoNq/7TKkJZpb3CDAE3H0yd3SEdZczzgkCsMpqZo9kf/moMlmmr11XpCjoBNITMZyTN7Oc5MwY8Dizi2CjShfWCkLpWMKYrjOSPM0OviKVLhdpZZqsfV7KkpEtZo=
